# DO NOT CHANGE the "init" and "install" sections below

image:
  - Visual Studio 2017

platform:
  - x64

# Use R 3.5.0 for compatibility
environment:
  R_VERSION: 3.5.0

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:

# Adapt as necessary starting from here

# Disable trigger on tags
for:
-
  skip_tags: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

# Prepare for deployment
before_deploy:
  - ps: |
          $env:PKGVER = Select-String -Path .\DESCRIPTION -Pattern '^Version: ' | % {$_.line -replace "^Version: "}
          $env:PKGNAME = Select-String -Path .\DESCRIPTION -Pattern '^Package: ' | % {$_.line -replace "^Package: "}
          $SRC_PKG_FILE = "${env:PKGNAME}_$env:PKGVER"
          Write-Host "File is $SRC_PKG_FILE"
          $env:BIN_PKG_FILE = Get-ChildItem -Path . | Where-Object { $_.Extension -eq ".zip" }
          Write-Host "Resulting binary: $env:BIN_PKG_FILE"

# Deploy to Github release
deploy:
  tag: '$(PKGNAME)-v$(PKGVER)'
  release: '$(PKGNAME)-v$(PKGVER)'
  description: ''
  provider: GitHub
  auth_token:
    secure: OdbBHimgFSQVDMZeZ1vpPrvNG6NvQz/fsvhCwLgi3omdj+oX2//xF6Qa9f+8jTP9
  artifact: $(BIN_PKG_FILE)
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
