---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# R-eca - Estimating Catch-at-Age

Reca is a package made for the Institute of Marine Research, by the Norwegian computing centre. The package produces predictions of catch-at-age,
i.e. the number of fish caught within each age group, of different fish stocks in commercial catches.

Predicting the catch-at-age of commercial fish stocks provides important input to stock assessment, and the quota-setting process.
The Norwegian Computing Center and the Institute of Marine Research have over years developed a Bayesian
hierarchical model to estimate the catch-at-age of fish. 
The model aims to estimate both the proportion-at-age and the mean weight of fish, in order to estimate 
total numbers at age from landing statistics (total landed weight og stock).


## Maintainance policy
The primary source for the Reca package is the repository maintained by the Norwegian computing centre: https://github.com/NorskRegnesentral/Reca, which comes with binaries pre-built for windows and linux. This fork is maintained to document configurations that allow for compiling the library for different operating systems, and to maintain a copy of depedencies that are no longer hosted by their original developers. Successful builds are archived in https://github.com/StoXProject/repo/tree/gh-pages. As a side effect this also provides a mac-version for some past releases of mac-os and R, but we are not committed to maintain this workflow, and adaptations to new os or R releases will have low priority.

## Tests
This repository contains some minimal testing. It runs ECA with some different data and model configurations and checks that it returns correctly formatted output. As the software environment is updated to new operating systems, new versions of R, etc., these tests facilitate detection of crashes, but does not detect unintended changes in output or mismatch between function documentation and implementation with respect to data formatting and configuration options. Some more elaborate testing is provided in the package RstoxFDA (https://github.com/StoXProject/RstoxFDA), which interfaces Reca.
